apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-15T09:56:28Z"
  generateName: grafana-6cf6665d5c-
  labels:
    app: grafana
    pod-template-hash: 6cf6665d5c
  name: grafana-6cf6665d5c-sjvm6
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: grafana-6cf6665d5c
    uid: 393d990a-2900-4207-b969-dabeee2114eb
  resourceVersion: "147028"
  uid: ac8356a7-ecfe-4781-b8ce-f6c84f209d92
spec:
  containers:
  - image: grafana/grafana:latest
    imagePullPolicy: Always
    name: grafana
    ports:
    - containerPort: 3000
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nmczg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-argocd-cluster-2-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-nmczg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-09-15T09:56:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-09-15T15:25:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-09-15T15:25:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-09-15T09:56:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://5e56b8033811782ce0314d33a61b00de72fbf485dd9b61b6fddd0e6de9279fe3
    image: docker.io/grafana/grafana:latest
    imageID: docker.io/grafana/grafana@sha256:408afb9726de5122b00a2576763a8a57a3c86d5b0eff5305bc994ceb3eb96c3f
    lastState:
      terminated:
        containerID: containerd://2b02cce1621d975fe1cfbd1200af209e162c51b1989cca10d6660c4f211a25aa
        exitCode: 255
        finishedAt: "2024-09-15T15:25:31Z"
        reason: Unknown
        startedAt: "2024-09-15T09:56:31Z"
    name: grafana
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-09-15T15:25:39Z"
  hostIP: 172.20.0.4
  phase: Running
  podIP: 10.42.3.245
  podIPs:
  - ip: 10.42.3.245
  qosClass: BestEffort
  startTime: "2024-09-15T09:56:28Z"
