apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/surendranaidu/argocd-public-repo.git'
    path: grafana
    targetRevision: HEAD
    helm:
      parameters:
        - name: "image.tag"
          value: "9.0.0"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

