apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/surendranaidu/argocd-public-repo.git'
    targetRevision: HEAD
    path: 'prometheus'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

